annotated-types==0.7.0
anyio==4.4.0
certifi==2024.6.2
charset-normalizer==3.3.2
click==8.1.7
colorama==0.4.6
decorator==5.1.1
distro==1.9.0
easydict==1.13
exceptiongroup==1.2.1
filelock==3.15.4
fsspec==2024.6.0
future==1.0.0
geocoder==1.38.1
gradio_client==0.16.1
h11==0.14.0
httpcore==1.0.5
httpx==0.27.0
huggingface-hub==0.23.4
idna==3.7
lxml==5.2.1
MouseInfo==0.1.3
openai==1.34.0
packaging==24.1
pillow==10.2.0
PyAutoGUI==0.9.54
pydantic==2.7.4
pydantic_core==2.18.4
PyGetWindow==0.0.9
PyMsgBox==1.0.9
pyperclip==1.8.2
pypinyin==0.51.0
PyRect==0.2.0
PyScreeze==0.1.30
pytweening==1.2.0
pywin32==306
PyYAML==6.0.1
ratelim==0.1.6
requests==2.32.3
six==1.16.0
sniffio==1.3.1
tqdm==4.66.4
typing_extensions==4.12.2
urllib3==2.2.2
websockets==11.0.3
